### ISSUE TITLE
Oddcast error

### ISSUE THREAD

**Issue by drkorobov** [supersu-man/pyt2s#3]
`from pyt2s.services import oddcast
obj = oddcast.Oddcast()

# Default Voice
data = obj.requestTTS('Lorem Ipsum is simply dummy text.Lorem Ipsum is simply dummy text')

# Custom Voice
data = obj.requestTTS('Lorem Ipsum is simply dummy text.Lorem Ipsum is simply dummy text', '6-2-1')

with open('output.mp3', '+wb') as file:
    file.write(data)`

Get mp3 file with text = {"CODE":204,"ERRORSTR":"Authorization%20failure."}

**Comment by supersu-man** [comment]
Fixed with [Release v0.0.4](https://github.com/supersu-man/pyt2s/releases/tag/0.0.4). Also checkout [updated docs](https://github.com/supersu-man/pyt2s?tab=readme-ov-file#usage).
